[package]
name = "pyrut"
version = "0.1.0"
authors = ["djKooks <inylove82@gmail.com>"]

[lib]
name = "pyrut"
crate-type = ["cdylib"]

[dependencies.cpython]
version = "0.2"
features = ["extension-module"]
